### ISSUE TITLE
ava/no-ignored-test-files causes error

### ISSUE THREAD

**Issue by btkostner** [AtomLinter/linter-eslint#1083]
## Issue Type

Bug

## Issue Description

Test files with `ava/no-ignored-test-files` linting error, while `eslint` command passes.

I've tried to track down the issue, but from what I can see, all the correct params are being sent to `eslint-plugin-ava`. This could be an issue on their end, but seeing as it works with the regular `eslint` command, I felt this was a better place to file an issue first.

I checked using the normal ava test globs, and those are also failing.

![screenshot from 2018-01-19 12 00 51](https://user-images.githubusercontent.com/3385679/35166827-6c8868b0-fd10-11e7-9211-37cd0b35dffa.png)

## Files

`.eslintrc.yml`
```yml
---

root: true

parserOptions:
  parser: 'babel-eslint'
  sourceType: 'module'

env:
  browser: true
  node: true

extends:
  - standard
  - plugin:vue/recommended
  - plugin:ava/recommended

plugins:
  - ava

rules:
  comma-dangle: ['error', 'always-multiline']

  # BUG: Ensures indentation for <script> tags starts at 2
  indent: off
  indent-legacy: ['error', 2]

  # Skipping tests is actually useful for future work
  ava/no-skip-test: off

  vue/max-attributes-per-line:
    singleline: 3

  # This is the default recommended with some custom keys added
  # https://github.com/vuejs/eslint-plugin-vue/blob/master/lib/rules/order-in-components.js
  vue/order-in-components:
    - error
    -
      - el
      - name
      - parent
      - functional
      - ['delimiters', 'comments']
      - ['components', 'directives', 'filters']
      - extends
      - mixins
      - inheritAttrs
      - model
      - meta
      - layout
      - ['props', 'propsData']
      - data
      - computed
      - watch
      - LIFECYCLE_HOOKS
      - load
      - methods
      - ['template', 'render']
      - renderError
```

`package.json`
```json
...
  "ava": {
    "babel": "inherit",
    "files": [
      "**/*.integration.js",
      "**/*.spec.js"
    ],
    "require": [
      "babel-register",
      "./test/bootstrap.js"
    ],
    "snapshotDir": "./test/snapshots"
  }
```

## Bug Checklist
- [X] Restart Atom
- [X] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [X] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.22.0-beta1
linter-eslint version: 8.4.0
ESLint version: 4.15.0
Hours since last Atom restart: 0
Platform: linux
Using local project ESLint from: /home/btkostner/Projects/system76/tachi/node_modules/eslint
Current file's scopes: [
  "source.js"
]
linter-eslint configuration: {
  "ignoreFixableRulesWhileTyping": true,
  "lintHtmlFiles": true,
  "rulesToSilenceWhileTyping": [
    "eol-last",
    "ava/no-ignored-test-files"
  ],
  "useGlobalEslint": false,
  "showRuleIdInMessage": true,
  "disableWhenNoEslintConfig": true,
  "eslintrcPath": "",
  "globalNodePath": "",
  "advancedLocalNodeModules": "",
  "eslintRulesDirs": [],
  "disableEslintIgnore": false,
  "disableFSCache": false,
  "fixOnSave": false,
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.babel",
    "source.js-semantic"
  ],
  "rulesToDisableWhileFixing": []
}
```
