### ISSUE TITLE
Errors doing TypeScript transpilation

### ISSUE THREAD

**Issue by benknight** [AtomLinter/linter-eslint#1298]
## Issue Type
Bug

## Issue Description
TypeScript transpilation seems to be failing when my ESLint config is parsed.
Multiple errors that looks like this:
```
Resolve error: ENOENT, node_modules/typescript/bin/lib.d.ts not found in /Applications/Atom.app/Contents/Resources/app.asar (import/no-named-as-default)
```
![image](https://user-images.githubusercontent.com/786691/63009811-62f09900-beaf-11e9-85ab-c91a58b09753.png)

.eslint.yaml looks like this (note the path to a webpack config written in TypeScript):

```yaml
extends:
  - prettier
  - prettier/@typescript-eslint
  - prettier/react
  - prettier/standard

env:
  browser: true

globals:
  __DEV__: true
  __ENV__: true

plugins:
  - prettier

settings:
  import/resolver:
    webpack:
      config: ./webpack/client.config.ts

rules:
  prettier/prettier: error
  react/jsx-boolean-value: always
  react/jsx-filename-extension:
    - 1
    - extensions:
        - '.ts'
        - '.tsx'
        - '.js'
        - '.jsx'
```

## Bug Checklist
- [x] Restart Atom
- [x] Verify the `eslint` CLI gives the proper result, while `linter-eslint` does not
- [x] Paste the output of the `Linter Eslint: Debug` command from the Command Palette below

```
Atom version: 1.40.0
linter-eslint version: 8.5.5
ESLint version: 5.13.0
Hours since last Atom restart: 0.2
Platform: darwin
Using local project ESLint from: [redacted]/node_modules/eslint
Current file's scopes: [
  "source.tsx",
  "source.ts",
  "support.variable"
]
linter-eslint configuration: {
  "disabling": {
    "disableWhenNoEslintConfig": false,
    "rulesToSilenceWhileTyping": []
  },
  "scopes": [
    "source.js",
    "source.jsx",
    "source.js.jsx",
    "source.flow",
    "source.babel",
    "source.js-semantic",
    "source.ts",
    "source.tsx"
  ],
  "lintHtmlFiles": false,
  "autofix": {
    "fixOnSave": false,
    "ignoreFixableRulesWhileTyping": false,
    "rulesToDisableWhileFixing": []
  },
  "global": {
    "useGlobalEslint": false,
    "eslintrcPath": "",
    "globalNodePath": ""
  },
  "advanced": {
    "disableEslintIgnore": false,
    "disableFSCache": false,
    "showRuleIdInMessage": true,
    "eslintRulesDirs": [],
    "localNodeModules": ""
  }
}
```
