### ISSUE TITLE
Error: Path must be a string. Received null

### ISSUE THREAD

**Issue by 190n** [AtomLinter/linter-eslint#299]
Whenever I save a file, Atom gives me the following error:

```
TypeError: Path must be a string. Received null
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:477:5)
    at /home/ben/.atom/packages/linter-eslint/lib/worker.js:65:28
    at /home/ben/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:58:16
    at Array.forEach (native)
    at Communication.emit (/home/ben/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/node_modules/zm-event-kit/dist/Emitter.js:57:43)
    at Communication.gotMessage (/home/ben/.atom/packages/linter-eslint/node_modules/childprocess-promise/node_modules/sb-communication/dist/main.js:33:16)
    at process.<anonymous> (/home/ben/.atom/packages/linter-eslint/node_modules/childprocess-promise/dist/main.js:29:27)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
```

"Use Global ESLint" is on. I have a `.eslintrc` in my current directory, and an identical copy in my home directory:

```yml
---
env:
    browser: true
    commonjs: true
rules:
    space-before-keywords: 0
    space-before-function-paren: 0
    space-in-parens: 0
ecmaFeatures:
    modules: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructing: true
    forOf: true
    objectLiteralComputedProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    spread: true
    superInFunctions: true
    templateStrings: true
    arrowFunctions: true
    
...
```
