### ISSUE TITLE
Cannot read Rule IDs in Messages when using Atom Material UI theme

### ISSUE THREAD

**Issue by reneruiz** [AtomLinter/linter-eslint#482]
Hi team,

I turned on 'Show Rule ID in Messages' in linter-eslint's settings.

The eslint Rule ID inside the pill isn't legible though. Screenshot:
![Screenshot](http://f.cl.ly/items/3g2V0o2F2H2R3e370W3L/Image%202016-03-11%20at%2012.12.44%20PM.png)

My first thought was that maybe it's the [Atom Material UI](https://atom.io/themes/atom-material-ui) theme causing the issue, but I don't seem to have the problem with my other Atom linters, so I thought I would try here first.

Here's a snippet of how I have Atom Material UI theme configured if anyone would like to recreate:

```
"atom-material-ui":
    colors:
      abaseColor:
        red: 126
        green: 87
        blue: 194
        alpha: 1
      accentColor:
        red: 176
        green: 228
        blue: 87
        alpha: 1
      predefinedColor: "Purple"
    fonts: {}
    tabs: {}
    treeView:
      compactList: true
    ui:
      panelContrast: true
```

I'd be happy to provide any other information needed.

**Comment by steelbrain** [comment]
This has been fixed in an update, please update your package

**Comment by reneruiz** [comment]
I have 7.1.1 installed which appears to be the latest:
![Screenshot](http://clicky.reneruiz.me/fOF2/Image%202016-03-11%20at%2012.28.56%20PM.png)

All my packages are also up-to-date: 
![Screenshot](http://clicky.reneruiz.me/fOLD/Image%202016-03-11%20at%2012.30.36%20PM.png)

**Comment by steelbrain** [comment]
In that case, the theme might be messing up it's ui variables, can you please try this with another theme?

**Comment by reneruiz** [comment]
Here's a screenshot with Atom Dark:
![Screenshot](http://clicky.reneruiz.me/fOPt/Image%202016-03-11%20at%2012.33.23%20PM.png)

It's there but white on gray isn't great either. :confused:

**Comment by Mulder90** [comment]
Same problem here. A temp workaround is to add this rule into Atom `styles.less `  
```css
// CUSTOM ESLINT CSS
#linter-inline a.eslint {
  color: black;
}
```
