### ISSUE TITLE
eslintignore having no effect

### ISSUE THREAD

**Issue by DanPurdy** [AtomLinter/linter-eslint#495]
Hi guys,

My `.eslintignore` is ironically seeming to be ignored by this plugin

Atom `v1.7.0-beta0`,
linter-eslint `7.1.1`

simplified app structure

```
app -
  |
   models
    |_ abstract-model.js
    |_ abstract-model.spec.js
.eslintrc
.eslintignore
```

eslintignore contents:
```
**/*.spec.js
dist/
karma.conf.js
```

The problem is that abstract-model.spec.js is still being linted in atom which i don't want to happen for now due to not currently using the linter friendly assertions from `chai-lint`.

When using from the command line though it is ignored,
`node_modules/eslint/bin/eslint.js app/core/model/**.*.js -c .eslintrc` It runs fine and ignores the file

when i strip out the eslintignore file and run
`node_modules/eslint/bin/eslint.js app/core/model/**.*.js -c .eslintrc --ignore-pattern **/*.spec.js` 
it's also fine.

I've tried clearing out linter-eslint's node_modules folder and reinstalled the dependencies too

My `.eslintrc` file is below too if that helps

```
---
  extends:
    - airbnb/base
    - angular
  # ============================================================================
  # Rules
  # ============================================================================
  rules:

    valid-jsdoc:
      - 1
      -
        requireParamDescription: true
        requireReturnDescription: true
        requireReturn: false
        prefer:
          return: "returns"
        preferType:
          String: "string"
          Number: "number"
          Boolean: "boolean"
          object: "Object"
    require-jsdoc:
      - 1
      -
        require:
          FunctionDeclaration: true
          MethodDefinition: true
          ClassDeclaration: true

  # ============================================================================
  # Angular Specific
  # ============================================================================

    angular/module-getter: 0 # buggy
    angular/module-setter: 0 # buggy
    angular/no-service-method: 0 # Service methods allow us to use es6 classes

  # ============================================================================
  # Environment
  # ============================================================================
  env:
    browser: true
    es6: true

  # ============================================================================
  # Parser
  # ============================================================================
  parser: 'babel-eslint'
```

linter-eslint in my config
```
"linter-eslint":
    globalNodePath: "/Users/danpurdy/.nvm/versions/node/v4.2.4"
```

But all the settings visible in the settings panel
<img width="824" alt="screen shot 2016-03-21 at 11 34 51" src="https://cloud.githubusercontent.com/assets/1386054/13917495/16922674-ef59-11e5-9065-61c5b3364803.png">
