### ISSUE TITLE
Error: ignoredMessages.includes is not a function

### ISSUE THREAD

**Issue by phaux** [AtomLinter/linter-eslint#622]
It just stopped working all of the sudden

```
TypeError: ignoredMessages.includes is not a function
    at /home/nate/.atom/packages/linter-eslint/lib/worker.js:37:29
    at Array.filter (native)
    at lintJob (/home/nate/.atom/packages/linter-eslint/lib/worker.js:36:42)
    at /home/nate/.atom/packages/linter-eslint/lib/worker.js:69:20
    at Emitter.emit (/home/nate/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:70:19)
    at /home/nate/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:22:23
    at /home/nate/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:21:24
    at Emitter.emit (/home/nate/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-event-kit/lib/emitter.js:68:19)
    at Communication.parseMessage (/home/nate/.atom/packages/linter-eslint/node_modules/process-communication/node_modules/sb-communication/lib/main.js:63:18)
    at process.ProcessCommunication.messageCallback (/home/nate/.atom/packages/linter-eslint/node_modules/process-communication/lib/communication.js:35:27)
```

Config:
```yml
parser: babel-eslint
extends: eslint:recommended
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  node: true
  es6: true
```

Linter-ESLint 7.2.3
ESLint 2.13.1
