### ISSUE TITLE
Failed to load plugin node: Cannot find module 'eslint-plugin-node'

### ISSUE THREAD

**Issue by Moeriki** [AtomLinter/linter-eslint#721]
When I open the `eslint` project in Atom I get this error from `linter-eslint`.

```
Error: Failed to load plugin node: Cannot find module 'eslint-plugin-node'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    ...
```

`eslint` has this `.eslintrc.yml` config.

```yaml
root: true

plugins:
    - node
extends:
    - "./packages/eslint-config-eslint/default.yml"
    - "plugin:node/recommended"
```

The dependency is listed and correctly installed.

```sh
$ l node_modules | grep eslint
drwxr-xr-x    9 user  staff    306 Sep 27 14:43 eslint-plugin-node/
```

So I do notice `eslint` doesn't depend on `eslint`. That may be an issue since my `linter-eslint` is configured to use the local install.
